### ISSUE TITLE
ofxUI linker errors

### ISSUE THREAD

**Issue by Daandelange** [YCAMInterlab/Duration#40]
Hello,
I'm trying to compile Duration without success.  
I'm stuck on some linker errors with ofxUI. The app uses methods like `ofxUIRectangle::inside(ofVec3f)` _referenced from:_ `DurationController::drawTooltips()`.  
I can't find any fork of ofxUI where these methods exist... which version of ofxUI did you use ? 
Here's the raw linker output: [[LINK](http://pastebin.com/yfh8QzjN)]

I could try to fix them manually but it looks like everything is different with that version of ofxUI... 
I tried rebasing `ofxUI` on:
- [rezaali/ofxUI/commit 1f524f2](https://github.com/rezaali/ofxUI/commit/1f524f2c41c73113c7529703e6f3274fdcc19956) (closest to the latest Duration push date)  
- [obviousjim/ofxUI/master](https://github.com/obviousjim/ofxUI/commit/67377608152166c0579248626a51ecf794cee2a0)
- [rezaali/ofxUI/master](https://github.com/rezaali/ofxUI)

Amazing software btw! ^_^

**Comment by Daandelange** [comment]
Oh wait, nvm, got it to compile. :) 
I have no idea how I got past this... and why these linker errors were thrown.

I'll push an updated Xcode project later.

**Comment by obviousjim** [comment]
Thanks!

On Friday, May 8, 2015, Daan de Lange <notifications@github.com> wrote:

> Closed #40 <https://github.com/YCAMInterlab/Duration/issues/40>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YCAMInterlab/Duration/issues/40#event-300455629>.
>


-- 
- James

**Comment by Daandelange** [comment]
There you go :)
https://github.com/YCAMInterlab/Duration/pull/41
